repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: ./node_modules/.bin/eslint
        language: system
        types: [javascript]
        args: ["--fix"]

      - id: jsonlint
        name: jsonlint
        entry: ./node_modules/.bin/jsonlint
        language: system
        files: \.json$  
